development:
  adapter: postgresql
  host: localhost
  database: top_development
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: top_test
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: top_production
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000


